apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-applicationset
  namespace: my-app
spec:
  generators:
    - list:
        elements:
          - name: nginx-instance
            namespace: my-app
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: https://charts.bitnami.com/bitnami
        chart: nginx
        targetRevision: 15.5.2
        helm:
          releaseName: '{{name}}'
          values: |
            service:
              type: ClusterIP
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
